openapi: 3.0.3
info:
  title: Swagger Farminsight FPF Synchronization - OpenAPI 3.0
  description: |-
    Endpoints that the FPF Sensor Service provides for synchronization purposes
  termsOfService: TOS
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://anants-pi-cluster.de/api
tags:
  - name: sync
    description: Synchronization for Sensor configuration
paths:
  /synchronise:
    post:
      tags:
        - sync
      summary: Upload sensor configuration for synchronization
      operationId: postSensorConfiguration
      requestBody:
        description: Array of Sensors
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Sensor'
      responses:
        '200':
          description: Successful operation
        '404':
          description: Sensor not found
        '422':
          description: Validation exception
  /sensorInterval/{sensorId}:
    post:
      tags:
        - sync
      summary: Upload new sensor interval
      description: Uploads new measurement interval of Sensor
      operationId: postSensorInterval
      parameters:
        - name: sensorId
          in: path
          description: ID of Sensor that the Interval belong to
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Sensor measurement interval in seconds
        content:
          application/json:
            schema:
              type: integer
      responses:
        '200':
          description: Successful operation
        '404':
          description: Sensor not found
        '422':
          description: Validation exception
components:
  schemas:
    Sensor:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        location:
          type: string
        unit:
          type: string
          enum:
            - °C
            - °F
            - kg
        modelNr:
          type: string
        isActive:
          type: boolean
        intervalSeconds:
          type: integer