# Generated by Django 5.1.2 on 2024-11-29 20:40

import django.db.models.deletion
import django.utils.timezone
import farminsight_dashboard_backend.utils.api_key_generator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('systemRole', models.CharField(default='user', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FPF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('isPublic', models.BooleanField(default=False)),
                ('sensorServiceIp', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('apiKey', models.CharField(default=farminsight_dashboard_backend.utils.api_key_generator.generate_random_api_key, max_length=64)),
                ('apiKeyValidUntil', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('isPublic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('modelNr', models.CharField(max_length=256)),
                ('resolution', models.CharField(max_length=256)),
                ('isActive', models.BooleanField(default=False)),
                ('intervalSeconds', models.IntegerField()),
                ('snapshotUrl', models.CharField(max_length=256)),
                ('livestreamUrl', models.CharField(max_length=256)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='farminsight_dashboard_backend.fpf')),
            ],
        ),
        migrations.CreateModel(
            name='GrowingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('plants', models.CharField(max_length=256)),
                ('note', models.CharField(max_length=256)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growingCycles', to='farminsight_dashboard_backend.fpf')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measuredAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membershipRole', models.CharField(max_length=256)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.organization')),
            ],
        ),
        migrations.AddField(
            model_name='fpf',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.organization'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
                ('modelNr', models.CharField(max_length=256)),
                ('isActive', models.BooleanField(default=False)),
                ('intervalSeconds', models.IntegerField()),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farminsight_dashboard_backend.fpf')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='farminsight_dashboard_backend.camera')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fpf',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_name_per_organization'),
        ),
    ]
