# Generated by Django 5.1.2 on 2024-11-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0005_alter_userprofile_systemrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='FPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='farminsight_dashboard_backend.fpf'),
        ),
        migrations.AlterField(
            model_name='growingcycle',
            name='FPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growingCycles', to='farminsight_dashboard_backend.fpf'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='FPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farminsight_dashboard_backend.fpf'),
        ),
    ]
