# Generated by Django 5.1.2 on 2024-11-06 22:07

import farminsight_dashboard_backend.utils.api_key_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0006_alter_camera_fpf_alter_growingcycle_fpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpf',
            name='apiKey',
            field=models.CharField(default=farminsight_dashboard_backend.utils.api_key_generator.generate_random_api_key, max_length=64),
        ),
        migrations.AddField(
            model_name='fpf',
            name='apiKeyValidUntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fpf',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddConstraint(
            model_name='fpf',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_name_per_organization'),
        ),
    ]
