# Generated by Django 5.1.2 on 2024-11-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0006_alter_organization_name'),
        ('farminsight_dashboard_backend', '0007_fpf_apikey_fpf_apikeyvaliduntil_fpf_createdat_and_more'),
    ]

    operations = [
    ]
