# Generated by Django 5.1.2 on 2024-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0008_merge_20241107_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpf',
            name='cameraServiceIp',
        ),
        migrations.AddField(
            model_name='camera',
            name='livestreamUrl',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='snapshotUrl',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fpf',
            name='sensorServiceIp',
            field=models.CharField(max_length=256),
        ),
    ]
