# Generated by Django 5.1.2 on 2024-12-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0010_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farminsight_dashboard_backend.camera'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Snapshot',
        ),
    ]
