# Generated by Django 5.1.2 on 2024-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0012_alter_growingcycle_enddate_alter_growingcycle_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
    ]
