# Generated by Django 5.1.2 on 2024-12-28 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0013_singleusetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amountInKg', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('growingCycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farminsight_dashboard_backend.growingcycle')),
            ],
        ),
    ]
